[package]
name = "femkgpwa"
version = "1.0.0"
description = "MKG Desktop App"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
name = "femkgpwa_lib"
crate-type = ["cdylib"]
